/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSnapshot {
  'id' : ID,
  'monthlyViews' : bigint,
  'channelId' : ID,
  'owner' : Principal,
  'totalViews' : bigint,
  'date' : bigint,
  'subscribers' : bigint,
  'monthlyRevenue' : number,
}
export interface Channel {
  'id' : ID,
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'targetAudience' : string,
  'uploadFrequency' : string,
  'niche' : Niche,
}
export interface ContentIdea {
  'id' : ID,
  'status' : ScriptStatus,
  'title' : string,
  'owner' : Principal,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'niche' : Niche,
}
export interface DashboardStats {
  'totalViews' : bigint,
  'totalVideos' : bigint,
  'totalSubscribers' : bigint,
  'totalIdeas' : bigint,
  'totalRevenue' : number,
}
export type ID = bigint;
export type Niche = { 'finance' : null } |
  { 'other' : string } |
  { 'entertainment' : null } |
  { 'food' : null } |
  { 'travel' : null } |
  { 'tech' : null } |
  { 'education' : null } |
  { 'gaming' : null } |
  { 'lifestyle' : null } |
  { 'health' : null };
export interface RevenueEntry {
  'id' : ID,
  'channelId' : ID,
  'source' : RevenueSource,
  'owner' : Principal,
  'date' : bigint,
  'description' : string,
  'currency' : string,
  'amount' : number,
}
export type RevenueSource = { 'sponsorship' : null } |
  { 'merchandise' : null } |
  { 'other' : string } |
  { 'adsense' : null } |
  { 'affiliate' : null };
export interface ScriptSection { 'title' : string, 'content' : string }
export type ScriptStatus = { 'scripted' : null } |
  { 'idea' : null } |
  { 'published' : null } |
  { 'recorded' : null } |
  { 'archived' : null };
export type ScriptTone = { 'review' : null } |
  { 'other' : string } |
  { 'educational' : null } |
  { 'entertaining' : null } |
  { 'tutorial' : null } |
  { 'informative' : null } |
  { 'motivational' : null } |
  { 'commentary' : null } |
  { 'storytelling' : null };
export interface UserProfileView {
  'scripts' : Array<ID>,
  'revenueEntries' : Array<ID>,
  'name' : string,
  'createdAt' : bigint,
  'analyticsSnapshots' : Array<ID>,
  'channels' : Array<ID>,
  'contentIdeas' : Array<ID>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoScript {
  'id' : ID,
  'title' : string,
  'topic' : string,
  'owner' : Principal,
  'body' : ScriptSection,
  'hook' : ScriptSection,
  'createdAt' : bigint,
  'tone' : ScriptTone,
  'callToAction' : ScriptSection,
  'niche' : Niche,
  'intro' : ScriptSection,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAnalyticsSnapshot' : ActorMethod<
    [ID, bigint, bigint, bigint, number, bigint],
    AnalyticsSnapshot
  >,
  'createChannel' : ActorMethod<
    [string, Niche, string, string, string],
    Channel
  >,
  'createContentIdea' : ActorMethod<
    [string, string, Array<string>, Niche, ScriptStatus],
    ContentIdea
  >,
  'createRevenueEntry' : ActorMethod<
    [ID, RevenueSource, number, string, bigint, string],
    RevenueEntry
  >,
  'createVideoScript' : ActorMethod<
    [
      string,
      Niche,
      ScriptTone,
      string,
      ScriptSection,
      ScriptSection,
      ScriptSection,
      ScriptSection,
    ],
    VideoScript
  >,
  'deleteAnalyticsSnapshot' : ActorMethod<[ID], undefined>,
  'deleteChannel' : ActorMethod<[ID], undefined>,
  'deleteContentIdea' : ActorMethod<[ID], undefined>,
  'deleteRevenueEntry' : ActorMethod<[ID], undefined>,
  'deleteVideoScript' : ActorMethod<[ID], undefined>,
  'getAllAnalyticsSnapshots' : ActorMethod<[], Array<AnalyticsSnapshot>>,
  'getAllChannels' : ActorMethod<[], Array<Channel>>,
  'getAllContentIdeas' : ActorMethod<[], Array<ContentIdea>>,
  'getAllRevenueEntries' : ActorMethod<[], Array<RevenueEntry>>,
  'getAllVideoScripts' : ActorMethod<[], Array<VideoScript>>,
  'getAnalyticsSnapshot' : ActorMethod<[ID], AnalyticsSnapshot>,
  'getCallerUserProfile' : ActorMethod<[], UserProfileView>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannel' : ActorMethod<[ID], Channel>,
  'getContentIdea' : ActorMethod<[ID], ContentIdea>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMyAnalyticsSnapshots' : ActorMethod<[], Array<AnalyticsSnapshot>>,
  'getMyChannels' : ActorMethod<[], Array<Channel>>,
  'getMyContentIdeas' : ActorMethod<[], Array<ContentIdea>>,
  'getMyRevenueEntries' : ActorMethod<[], Array<RevenueEntry>>,
  'getMyVideoScripts' : ActorMethod<[], Array<VideoScript>>,
  'getRevenueEntry' : ActorMethod<[ID], RevenueEntry>,
  'getUserProfile' : ActorMethod<[Principal], UserProfileView>,
  'getVideoScript' : ActorMethod<[ID], VideoScript>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileView], undefined>,
  'updateAnalyticsSnapshot' : ActorMethod<
    [ID, ID, bigint, bigint, bigint, number, bigint],
    AnalyticsSnapshot
  >,
  'updateChannel' : ActorMethod<
    [ID, string, Niche, string, string, string],
    Channel
  >,
  'updateContentIdea' : ActorMethod<
    [ID, string, string, Array<string>, Niche, ScriptStatus],
    ContentIdea
  >,
  'updateRevenueEntry' : ActorMethod<
    [ID, ID, RevenueSource, number, string, bigint, string],
    RevenueEntry
  >,
  'updateVideoScript' : ActorMethod<
    [
      ID,
      string,
      Niche,
      ScriptTone,
      string,
      ScriptSection,
      ScriptSection,
      ScriptSection,
      ScriptSection,
    ],
    VideoScript
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];