/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ID = IDL.Nat;
export const AnalyticsSnapshot = IDL.Record({
  'id' : ID,
  'monthlyViews' : IDL.Nat,
  'channelId' : ID,
  'owner' : IDL.Principal,
  'totalViews' : IDL.Nat,
  'date' : IDL.Int,
  'subscribers' : IDL.Nat,
  'monthlyRevenue' : IDL.Float64,
});
export const Niche = IDL.Variant({
  'finance' : IDL.Null,
  'other' : IDL.Text,
  'entertainment' : IDL.Null,
  'food' : IDL.Null,
  'travel' : IDL.Null,
  'tech' : IDL.Null,
  'education' : IDL.Null,
  'gaming' : IDL.Null,
  'lifestyle' : IDL.Null,
  'health' : IDL.Null,
});
export const Channel = IDL.Record({
  'id' : ID,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'targetAudience' : IDL.Text,
  'uploadFrequency' : IDL.Text,
  'niche' : Niche,
});
export const ScriptStatus = IDL.Variant({
  'scripted' : IDL.Null,
  'idea' : IDL.Null,
  'published' : IDL.Null,
  'recorded' : IDL.Null,
  'archived' : IDL.Null,
});
export const ContentIdea = IDL.Record({
  'id' : ID,
  'status' : ScriptStatus,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'niche' : Niche,
});
export const RevenueSource = IDL.Variant({
  'sponsorship' : IDL.Null,
  'merchandise' : IDL.Null,
  'other' : IDL.Text,
  'adsense' : IDL.Null,
  'affiliate' : IDL.Null,
});
export const RevenueEntry = IDL.Record({
  'id' : ID,
  'channelId' : ID,
  'source' : RevenueSource,
  'owner' : IDL.Principal,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'amount' : IDL.Float64,
});
export const ScriptTone = IDL.Variant({
  'review' : IDL.Null,
  'other' : IDL.Text,
  'educational' : IDL.Null,
  'entertaining' : IDL.Null,
  'tutorial' : IDL.Null,
  'informative' : IDL.Null,
  'motivational' : IDL.Null,
  'commentary' : IDL.Null,
  'storytelling' : IDL.Null,
});
export const ScriptSection = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const VideoScript = IDL.Record({
  'id' : ID,
  'title' : IDL.Text,
  'topic' : IDL.Text,
  'owner' : IDL.Principal,
  'body' : ScriptSection,
  'hook' : ScriptSection,
  'createdAt' : IDL.Int,
  'tone' : ScriptTone,
  'callToAction' : ScriptSection,
  'niche' : Niche,
  'intro' : ScriptSection,
});
export const UserProfileView = IDL.Record({
  'scripts' : IDL.Vec(ID),
  'revenueEntries' : IDL.Vec(ID),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'analyticsSnapshots' : IDL.Vec(ID),
  'channels' : IDL.Vec(ID),
  'contentIdeas' : IDL.Vec(ID),
});
export const DashboardStats = IDL.Record({
  'totalViews' : IDL.Nat,
  'totalVideos' : IDL.Nat,
  'totalSubscribers' : IDL.Nat,
  'totalIdeas' : IDL.Nat,
  'totalRevenue' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnalyticsSnapshot' : IDL.Func(
      [ID, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64, IDL.Int],
      [AnalyticsSnapshot],
      [],
    ),
  'createChannel' : IDL.Func(
      [IDL.Text, Niche, IDL.Text, IDL.Text, IDL.Text],
      [Channel],
      [],
    ),
  'createContentIdea' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), Niche, ScriptStatus],
      [ContentIdea],
      [],
    ),
  'createRevenueEntry' : IDL.Func(
      [ID, RevenueSource, IDL.Float64, IDL.Text, IDL.Int, IDL.Text],
      [RevenueEntry],
      [],
    ),
  'createVideoScript' : IDL.Func(
      [
        IDL.Text,
        Niche,
        ScriptTone,
        IDL.Text,
        ScriptSection,
        ScriptSection,
        ScriptSection,
        ScriptSection,
      ],
      [VideoScript],
      [],
    ),
  'deleteAnalyticsSnapshot' : IDL.Func([ID], [], []),
  'deleteChannel' : IDL.Func([ID], [], []),
  'deleteContentIdea' : IDL.Func([ID], [], []),
  'deleteRevenueEntry' : IDL.Func([ID], [], []),
  'deleteVideoScript' : IDL.Func([ID], [], []),
  'getAllAnalyticsSnapshots' : IDL.Func(
      [],
      [IDL.Vec(AnalyticsSnapshot)],
      ['query'],
    ),
  'getAllChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'getAllContentIdeas' : IDL.Func([], [IDL.Vec(ContentIdea)], ['query']),
  'getAllRevenueEntries' : IDL.Func([], [IDL.Vec(RevenueEntry)], ['query']),
  'getAllVideoScripts' : IDL.Func([], [IDL.Vec(VideoScript)], ['query']),
  'getAnalyticsSnapshot' : IDL.Func([ID], [AnalyticsSnapshot], ['query']),
  'getCallerUserProfile' : IDL.Func([], [UserProfileView], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannel' : IDL.Func([ID], [Channel], ['query']),
  'getContentIdea' : IDL.Func([ID], [ContentIdea], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMyAnalyticsSnapshots' : IDL.Func(
      [],
      [IDL.Vec(AnalyticsSnapshot)],
      ['query'],
    ),
  'getMyChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'getMyContentIdeas' : IDL.Func([], [IDL.Vec(ContentIdea)], ['query']),
  'getMyRevenueEntries' : IDL.Func([], [IDL.Vec(RevenueEntry)], ['query']),
  'getMyVideoScripts' : IDL.Func([], [IDL.Vec(VideoScript)], ['query']),
  'getRevenueEntry' : IDL.Func([ID], [RevenueEntry], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfileView], ['query']),
  'getVideoScript' : IDL.Func([ID], [VideoScript], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfileView], [], []),
  'updateAnalyticsSnapshot' : IDL.Func(
      [ID, ID, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64, IDL.Int],
      [AnalyticsSnapshot],
      [],
    ),
  'updateChannel' : IDL.Func(
      [ID, IDL.Text, Niche, IDL.Text, IDL.Text, IDL.Text],
      [Channel],
      [],
    ),
  'updateContentIdea' : IDL.Func(
      [ID, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), Niche, ScriptStatus],
      [ContentIdea],
      [],
    ),
  'updateRevenueEntry' : IDL.Func(
      [ID, ID, RevenueSource, IDL.Float64, IDL.Text, IDL.Int, IDL.Text],
      [RevenueEntry],
      [],
    ),
  'updateVideoScript' : IDL.Func(
      [
        ID,
        IDL.Text,
        Niche,
        ScriptTone,
        IDL.Text,
        ScriptSection,
        ScriptSection,
        ScriptSection,
        ScriptSection,
      ],
      [VideoScript],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ID = IDL.Nat;
  const AnalyticsSnapshot = IDL.Record({
    'id' : ID,
    'monthlyViews' : IDL.Nat,
    'channelId' : ID,
    'owner' : IDL.Principal,
    'totalViews' : IDL.Nat,
    'date' : IDL.Int,
    'subscribers' : IDL.Nat,
    'monthlyRevenue' : IDL.Float64,
  });
  const Niche = IDL.Variant({
    'finance' : IDL.Null,
    'other' : IDL.Text,
    'entertainment' : IDL.Null,
    'food' : IDL.Null,
    'travel' : IDL.Null,
    'tech' : IDL.Null,
    'education' : IDL.Null,
    'gaming' : IDL.Null,
    'lifestyle' : IDL.Null,
    'health' : IDL.Null,
  });
  const Channel = IDL.Record({
    'id' : ID,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'targetAudience' : IDL.Text,
    'uploadFrequency' : IDL.Text,
    'niche' : Niche,
  });
  const ScriptStatus = IDL.Variant({
    'scripted' : IDL.Null,
    'idea' : IDL.Null,
    'published' : IDL.Null,
    'recorded' : IDL.Null,
    'archived' : IDL.Null,
  });
  const ContentIdea = IDL.Record({
    'id' : ID,
    'status' : ScriptStatus,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'niche' : Niche,
  });
  const RevenueSource = IDL.Variant({
    'sponsorship' : IDL.Null,
    'merchandise' : IDL.Null,
    'other' : IDL.Text,
    'adsense' : IDL.Null,
    'affiliate' : IDL.Null,
  });
  const RevenueEntry = IDL.Record({
    'id' : ID,
    'channelId' : ID,
    'source' : RevenueSource,
    'owner' : IDL.Principal,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const ScriptTone = IDL.Variant({
    'review' : IDL.Null,
    'other' : IDL.Text,
    'educational' : IDL.Null,
    'entertaining' : IDL.Null,
    'tutorial' : IDL.Null,
    'informative' : IDL.Null,
    'motivational' : IDL.Null,
    'commentary' : IDL.Null,
    'storytelling' : IDL.Null,
  });
  const ScriptSection = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const VideoScript = IDL.Record({
    'id' : ID,
    'title' : IDL.Text,
    'topic' : IDL.Text,
    'owner' : IDL.Principal,
    'body' : ScriptSection,
    'hook' : ScriptSection,
    'createdAt' : IDL.Int,
    'tone' : ScriptTone,
    'callToAction' : ScriptSection,
    'niche' : Niche,
    'intro' : ScriptSection,
  });
  const UserProfileView = IDL.Record({
    'scripts' : IDL.Vec(ID),
    'revenueEntries' : IDL.Vec(ID),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'analyticsSnapshots' : IDL.Vec(ID),
    'channels' : IDL.Vec(ID),
    'contentIdeas' : IDL.Vec(ID),
  });
  const DashboardStats = IDL.Record({
    'totalViews' : IDL.Nat,
    'totalVideos' : IDL.Nat,
    'totalSubscribers' : IDL.Nat,
    'totalIdeas' : IDL.Nat,
    'totalRevenue' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnalyticsSnapshot' : IDL.Func(
        [ID, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64, IDL.Int],
        [AnalyticsSnapshot],
        [],
      ),
    'createChannel' : IDL.Func(
        [IDL.Text, Niche, IDL.Text, IDL.Text, IDL.Text],
        [Channel],
        [],
      ),
    'createContentIdea' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), Niche, ScriptStatus],
        [ContentIdea],
        [],
      ),
    'createRevenueEntry' : IDL.Func(
        [ID, RevenueSource, IDL.Float64, IDL.Text, IDL.Int, IDL.Text],
        [RevenueEntry],
        [],
      ),
    'createVideoScript' : IDL.Func(
        [
          IDL.Text,
          Niche,
          ScriptTone,
          IDL.Text,
          ScriptSection,
          ScriptSection,
          ScriptSection,
          ScriptSection,
        ],
        [VideoScript],
        [],
      ),
    'deleteAnalyticsSnapshot' : IDL.Func([ID], [], []),
    'deleteChannel' : IDL.Func([ID], [], []),
    'deleteContentIdea' : IDL.Func([ID], [], []),
    'deleteRevenueEntry' : IDL.Func([ID], [], []),
    'deleteVideoScript' : IDL.Func([ID], [], []),
    'getAllAnalyticsSnapshots' : IDL.Func(
        [],
        [IDL.Vec(AnalyticsSnapshot)],
        ['query'],
      ),
    'getAllChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'getAllContentIdeas' : IDL.Func([], [IDL.Vec(ContentIdea)], ['query']),
    'getAllRevenueEntries' : IDL.Func([], [IDL.Vec(RevenueEntry)], ['query']),
    'getAllVideoScripts' : IDL.Func([], [IDL.Vec(VideoScript)], ['query']),
    'getAnalyticsSnapshot' : IDL.Func([ID], [AnalyticsSnapshot], ['query']),
    'getCallerUserProfile' : IDL.Func([], [UserProfileView], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannel' : IDL.Func([ID], [Channel], ['query']),
    'getContentIdea' : IDL.Func([ID], [ContentIdea], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMyAnalyticsSnapshots' : IDL.Func(
        [],
        [IDL.Vec(AnalyticsSnapshot)],
        ['query'],
      ),
    'getMyChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'getMyContentIdeas' : IDL.Func([], [IDL.Vec(ContentIdea)], ['query']),
    'getMyRevenueEntries' : IDL.Func([], [IDL.Vec(RevenueEntry)], ['query']),
    'getMyVideoScripts' : IDL.Func([], [IDL.Vec(VideoScript)], ['query']),
    'getRevenueEntry' : IDL.Func([ID], [RevenueEntry], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfileView], ['query']),
    'getVideoScript' : IDL.Func([ID], [VideoScript], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfileView], [], []),
    'updateAnalyticsSnapshot' : IDL.Func(
        [ID, ID, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64, IDL.Int],
        [AnalyticsSnapshot],
        [],
      ),
    'updateChannel' : IDL.Func(
        [ID, IDL.Text, Niche, IDL.Text, IDL.Text, IDL.Text],
        [Channel],
        [],
      ),
    'updateContentIdea' : IDL.Func(
        [ID, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), Niche, ScriptStatus],
        [ContentIdea],
        [],
      ),
    'updateRevenueEntry' : IDL.Func(
        [ID, ID, RevenueSource, IDL.Float64, IDL.Text, IDL.Int, IDL.Text],
        [RevenueEntry],
        [],
      ),
    'updateVideoScript' : IDL.Func(
        [
          ID,
          IDL.Text,
          Niche,
          ScriptTone,
          IDL.Text,
          ScriptSection,
          ScriptSection,
          ScriptSection,
          ScriptSection,
        ],
        [VideoScript],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };