/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ScriptSection {
    title: string;
    content: string;
}
export interface Channel {
    id: ID;
    owner: Principal;
    name: string;
    description: string;
    targetAudience: string;
    uploadFrequency: string;
    niche: Niche;
}
export interface VideoScript {
    id: ID;
    title: string;
    topic: string;
    owner: Principal;
    body: ScriptSection;
    hook: ScriptSection;
    createdAt: bigint;
    tone: ScriptTone;
    callToAction: ScriptSection;
    niche: Niche;
    intro: ScriptSection;
}
export interface RevenueEntry {
    id: ID;
    channelId: ID;
    source: RevenueSource;
    owner: Principal;
    date: bigint;
    description: string;
    currency: string;
    amount: number;
}
export interface DashboardStats {
    totalViews: bigint;
    totalVideos: bigint;
    totalSubscribers: bigint;
    totalIdeas: bigint;
    totalRevenue: number;
}
export type ID = bigint;
export interface AnalyticsSnapshot {
    id: ID;
    monthlyViews: bigint;
    channelId: ID;
    owner: Principal;
    totalViews: bigint;
    date: bigint;
    subscribers: bigint;
    monthlyRevenue: number;
}
export type Niche = {
    __kind__: "finance";
    finance: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "entertainment";
    entertainment: null;
} | {
    __kind__: "food";
    food: null;
} | {
    __kind__: "travel";
    travel: null;
} | {
    __kind__: "tech";
    tech: null;
} | {
    __kind__: "education";
    education: null;
} | {
    __kind__: "gaming";
    gaming: null;
} | {
    __kind__: "lifestyle";
    lifestyle: null;
} | {
    __kind__: "health";
    health: null;
};
export interface ContentIdea {
    id: ID;
    status: ScriptStatus;
    title: string;
    owner: Principal;
    createdAt: bigint;
    tags: Array<string>;
    description: string;
    niche: Niche;
}
export interface UserProfileView {
    scripts: Array<ID>;
    revenueEntries: Array<ID>;
    name: string;
    createdAt: bigint;
    analyticsSnapshots: Array<ID>;
    channels: Array<ID>;
    contentIdeas: Array<ID>;
}
export type ScriptTone = {
    __kind__: "review";
    review: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "educational";
    educational: null;
} | {
    __kind__: "entertaining";
    entertaining: null;
} | {
    __kind__: "tutorial";
    tutorial: null;
} | {
    __kind__: "informative";
    informative: null;
} | {
    __kind__: "motivational";
    motivational: null;
} | {
    __kind__: "commentary";
    commentary: null;
} | {
    __kind__: "storytelling";
    storytelling: null;
};
export type RevenueSource = {
    __kind__: "sponsorship";
    sponsorship: null;
} | {
    __kind__: "merchandise";
    merchandise: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "adsense";
    adsense: null;
} | {
    __kind__: "affiliate";
    affiliate: null;
};
export enum ScriptStatus {
    scripted = "scripted",
    idea = "idea",
    published = "published",
    recorded = "recorded",
    archived = "archived"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAnalyticsSnapshot(channelId: ID, subs: bigint, totalViews: bigint, monthlyViews: bigint, monthlyRevenue: number, date: bigint): Promise<AnalyticsSnapshot>;
    createChannel(name: string, niche: Niche, desc: string, uploadFreq: string, targetAudience: string): Promise<Channel>;
    createContentIdea(title: string, desc: string, tags: Array<string>, niche: Niche, status: ScriptStatus): Promise<ContentIdea>;
    createRevenueEntry(channelId: ID, source: RevenueSource, amount: number, currency: string, date: bigint, desc: string): Promise<RevenueEntry>;
    createVideoScript(title: string, niche: Niche, tone: ScriptTone, topic: string, hook: ScriptSection, intro: ScriptSection, body: ScriptSection, callToAction: ScriptSection): Promise<VideoScript>;
    deleteAnalyticsSnapshot(id: ID): Promise<void>;
    deleteChannel(id: ID): Promise<void>;
    deleteContentIdea(id: ID): Promise<void>;
    deleteRevenueEntry(id: ID): Promise<void>;
    deleteVideoScript(id: ID): Promise<void>;
    getAllAnalyticsSnapshots(): Promise<Array<AnalyticsSnapshot>>;
    getAllChannels(): Promise<Array<Channel>>;
    getAllContentIdeas(): Promise<Array<ContentIdea>>;
    getAllRevenueEntries(): Promise<Array<RevenueEntry>>;
    getAllVideoScripts(): Promise<Array<VideoScript>>;
    getAnalyticsSnapshot(id: ID): Promise<AnalyticsSnapshot>;
    getCallerUserProfile(): Promise<UserProfileView>;
    getCallerUserRole(): Promise<UserRole>;
    getChannel(id: ID): Promise<Channel>;
    getContentIdea(id: ID): Promise<ContentIdea>;
    getDashboardStats(): Promise<DashboardStats>;
    getMyAnalyticsSnapshots(): Promise<Array<AnalyticsSnapshot>>;
    getMyChannels(): Promise<Array<Channel>>;
    getMyContentIdeas(): Promise<Array<ContentIdea>>;
    getMyRevenueEntries(): Promise<Array<RevenueEntry>>;
    getMyVideoScripts(): Promise<Array<VideoScript>>;
    getRevenueEntry(id: ID): Promise<RevenueEntry>;
    getUserProfile(user: Principal): Promise<UserProfileView>;
    getVideoScript(id: ID): Promise<VideoScript>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfileView): Promise<void>;
    updateAnalyticsSnapshot(id: ID, channelId: ID, subs: bigint, totalViews: bigint, monthlyViews: bigint, monthlyRevenue: number, date: bigint): Promise<AnalyticsSnapshot>;
    updateChannel(id: ID, name: string, niche: Niche, desc: string, uploadFreq: string, targetAudience: string): Promise<Channel>;
    updateContentIdea(id: ID, title: string, desc: string, tags: Array<string>, niche: Niche, status: ScriptStatus): Promise<ContentIdea>;
    updateRevenueEntry(id: ID, channelId: ID, source: RevenueSource, amount: number, currency: string, date: bigint, desc: string): Promise<RevenueEntry>;
    updateVideoScript(id: ID, title: string, niche: Niche, tone: ScriptTone, topic: string, hook: ScriptSection, intro: ScriptSection, body: ScriptSection, callToAction: ScriptSection): Promise<VideoScript>;
}
import type { Channel as _Channel, ContentIdea as _ContentIdea, ID as _ID, Niche as _Niche, RevenueEntry as _RevenueEntry, RevenueSource as _RevenueSource, ScriptSection as _ScriptSection, ScriptStatus as _ScriptStatus, ScriptTone as _ScriptTone, UserRole as _UserRole, VideoScript as _VideoScript } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAnalyticsSnapshot(arg0: ID, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number, arg5: bigint): Promise<AnalyticsSnapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnalyticsSnapshot(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnalyticsSnapshot(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createChannel(arg0: string, arg1: Niche, arg2: string, arg3: string, arg4: string): Promise<Channel> {
        if (this.processError) {
            try {
                const result = await this.actor.createChannel(arg0, to_candid_Niche_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return from_candid_Channel_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChannel(arg0, to_candid_Niche_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return from_candid_Channel_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createContentIdea(arg0: string, arg1: string, arg2: Array<string>, arg3: Niche, arg4: ScriptStatus): Promise<ContentIdea> {
        if (this.processError) {
            try {
                const result = await this.actor.createContentIdea(arg0, arg1, arg2, to_candid_Niche_n3(this._uploadFile, this._downloadFile, arg3), to_candid_ScriptStatus_n9(this._uploadFile, this._downloadFile, arg4));
                return from_candid_ContentIdea_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContentIdea(arg0, arg1, arg2, to_candid_Niche_n3(this._uploadFile, this._downloadFile, arg3), to_candid_ScriptStatus_n9(this._uploadFile, this._downloadFile, arg4));
            return from_candid_ContentIdea_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRevenueEntry(arg0: ID, arg1: RevenueSource, arg2: number, arg3: string, arg4: bigint, arg5: string): Promise<RevenueEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.createRevenueEntry(arg0, to_candid_RevenueSource_n15(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return from_candid_RevenueEntry_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRevenueEntry(arg0, to_candid_RevenueSource_n15(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return from_candid_RevenueEntry_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createVideoScript(arg0: string, arg1: Niche, arg2: ScriptTone, arg3: string, arg4: ScriptSection, arg5: ScriptSection, arg6: ScriptSection, arg7: ScriptSection): Promise<VideoScript> {
        if (this.processError) {
            try {
                const result = await this.actor.createVideoScript(arg0, to_candid_Niche_n3(this._uploadFile, this._downloadFile, arg1), to_candid_ScriptTone_n21(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7);
                return from_candid_VideoScript_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVideoScript(arg0, to_candid_Niche_n3(this._uploadFile, this._downloadFile, arg1), to_candid_ScriptTone_n21(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7);
            return from_candid_VideoScript_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAnalyticsSnapshot(arg0: ID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnalyticsSnapshot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnalyticsSnapshot(arg0);
            return result;
        }
    }
    async deleteChannel(arg0: ID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChannel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChannel(arg0);
            return result;
        }
    }
    async deleteContentIdea(arg0: ID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContentIdea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContentIdea(arg0);
            return result;
        }
    }
    async deleteRevenueEntry(arg0: ID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRevenueEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRevenueEntry(arg0);
            return result;
        }
    }
    async deleteVideoScript(arg0: ID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideoScript(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideoScript(arg0);
            return result;
        }
    }
    async getAllAnalyticsSnapshots(): Promise<Array<AnalyticsSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnalyticsSnapshots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnalyticsSnapshots();
            return result;
        }
    }
    async getAllChannels(): Promise<Array<Channel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChannels();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChannels();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContentIdeas(): Promise<Array<ContentIdea>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContentIdeas();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContentIdeas();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRevenueEntries(): Promise<Array<RevenueEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRevenueEntries();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRevenueEntries();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVideoScripts(): Promise<Array<VideoScript>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideoScripts();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideoScripts();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalyticsSnapshot(arg0: ID): Promise<AnalyticsSnapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsSnapshot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsSnapshot(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfileView> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannel(arg0: ID): Promise<Channel> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannel(arg0);
                return from_candid_Channel_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannel(arg0);
            return from_candid_Channel_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContentIdea(arg0: ID): Promise<ContentIdea> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentIdea(arg0);
                return from_candid_ContentIdea_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentIdea(arg0);
            return from_candid_ContentIdea_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getMyAnalyticsSnapshots(): Promise<Array<AnalyticsSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAnalyticsSnapshots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAnalyticsSnapshots();
            return result;
        }
    }
    async getMyChannels(): Promise<Array<Channel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyChannels();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyChannels();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyContentIdeas(): Promise<Array<ContentIdea>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyContentIdeas();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyContentIdeas();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRevenueEntries(): Promise<Array<RevenueEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRevenueEntries();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRevenueEntries();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyVideoScripts(): Promise<Array<VideoScript>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVideoScripts();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVideoScripts();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRevenueEntry(arg0: ID): Promise<RevenueEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueEntry(arg0);
                return from_candid_RevenueEntry_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueEntry(arg0);
            return from_candid_RevenueEntry_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfileView> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return result;
        }
    }
    async getVideoScript(arg0: ID): Promise<VideoScript> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoScript(arg0);
                return from_candid_VideoScript_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoScript(arg0);
            return from_candid_VideoScript_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfileView): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateAnalyticsSnapshot(arg0: ID, arg1: ID, arg2: bigint, arg3: bigint, arg4: bigint, arg5: number, arg6: bigint): Promise<AnalyticsSnapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnalyticsSnapshot(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnalyticsSnapshot(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateChannel(arg0: ID, arg1: string, arg2: Niche, arg3: string, arg4: string, arg5: string): Promise<Channel> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChannel(arg0, arg1, to_candid_Niche_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return from_candid_Channel_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChannel(arg0, arg1, to_candid_Niche_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return from_candid_Channel_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateContentIdea(arg0: ID, arg1: string, arg2: string, arg3: Array<string>, arg4: Niche, arg5: ScriptStatus): Promise<ContentIdea> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContentIdea(arg0, arg1, arg2, arg3, to_candid_Niche_n3(this._uploadFile, this._downloadFile, arg4), to_candid_ScriptStatus_n9(this._uploadFile, this._downloadFile, arg5));
                return from_candid_ContentIdea_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContentIdea(arg0, arg1, arg2, arg3, to_candid_Niche_n3(this._uploadFile, this._downloadFile, arg4), to_candid_ScriptStatus_n9(this._uploadFile, this._downloadFile, arg5));
            return from_candid_ContentIdea_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRevenueEntry(arg0: ID, arg1: ID, arg2: RevenueSource, arg3: number, arg4: string, arg5: bigint, arg6: string): Promise<RevenueEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRevenueEntry(arg0, arg1, to_candid_RevenueSource_n15(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return from_candid_RevenueEntry_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRevenueEntry(arg0, arg1, to_candid_RevenueSource_n15(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return from_candid_RevenueEntry_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateVideoScript(arg0: ID, arg1: string, arg2: Niche, arg3: ScriptTone, arg4: string, arg5: ScriptSection, arg6: ScriptSection, arg7: ScriptSection, arg8: ScriptSection): Promise<VideoScript> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideoScript(arg0, arg1, to_candid_Niche_n3(this._uploadFile, this._downloadFile, arg2), to_candid_ScriptTone_n21(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8);
                return from_candid_VideoScript_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideoScript(arg0, arg1, to_candid_Niche_n3(this._uploadFile, this._downloadFile, arg2), to_candid_ScriptTone_n21(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8);
            return from_candid_VideoScript_n23(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Channel_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Channel): Channel {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ContentIdea_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentIdea): ContentIdea {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Niche_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Niche): Niche {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_RevenueEntry_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RevenueEntry): RevenueEntry {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_RevenueSource_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RevenueSource): RevenueSource {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ScriptStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScriptStatus): ScriptStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ScriptTone_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScriptTone): ScriptTone {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_VideoScript_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoScript): VideoScript {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ID;
    status: _ScriptStatus;
    title: string;
    owner: Principal;
    createdAt: bigint;
    tags: Array<string>;
    description: string;
    niche: _Niche;
}): {
    id: ID;
    status: ScriptStatus;
    title: string;
    owner: Principal;
    createdAt: bigint;
    tags: Array<string>;
    description: string;
    niche: Niche;
} {
    return {
        id: value.id,
        status: from_candid_ScriptStatus_n13(_uploadFile, _downloadFile, value.status),
        title: value.title,
        owner: value.owner,
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        niche: from_candid_Niche_n7(_uploadFile, _downloadFile, value.niche)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ID;
    channelId: _ID;
    source: _RevenueSource;
    owner: Principal;
    date: bigint;
    description: string;
    currency: string;
    amount: number;
}): {
    id: ID;
    channelId: ID;
    source: RevenueSource;
    owner: Principal;
    date: bigint;
    description: string;
    currency: string;
    amount: number;
} {
    return {
        id: value.id,
        channelId: value.channelId,
        source: from_candid_RevenueSource_n19(_uploadFile, _downloadFile, value.source),
        owner: value.owner,
        date: value.date,
        description: value.description,
        currency: value.currency,
        amount: value.amount
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ID;
    title: string;
    topic: string;
    owner: Principal;
    body: _ScriptSection;
    hook: _ScriptSection;
    createdAt: bigint;
    tone: _ScriptTone;
    callToAction: _ScriptSection;
    niche: _Niche;
    intro: _ScriptSection;
}): {
    id: ID;
    title: string;
    topic: string;
    owner: Principal;
    body: ScriptSection;
    hook: ScriptSection;
    createdAt: bigint;
    tone: ScriptTone;
    callToAction: ScriptSection;
    niche: Niche;
    intro: ScriptSection;
} {
    return {
        id: value.id,
        title: value.title,
        topic: value.topic,
        owner: value.owner,
        body: value.body,
        hook: value.hook,
        createdAt: value.createdAt,
        tone: from_candid_ScriptTone_n25(_uploadFile, _downloadFile, value.tone),
        callToAction: value.callToAction,
        niche: from_candid_Niche_n7(_uploadFile, _downloadFile, value.niche),
        intro: value.intro
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ID;
    owner: Principal;
    name: string;
    description: string;
    targetAudience: string;
    uploadFrequency: string;
    niche: _Niche;
}): {
    id: ID;
    owner: Principal;
    name: string;
    description: string;
    targetAudience: string;
    uploadFrequency: string;
    niche: Niche;
} {
    return {
        id: value.id,
        owner: value.owner,
        name: value.name,
        description: value.description,
        targetAudience: value.targetAudience,
        uploadFrequency: value.uploadFrequency,
        niche: from_candid_Niche_n7(_uploadFile, _downloadFile, value.niche)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scripted: null;
} | {
    idea: null;
} | {
    published: null;
} | {
    recorded: null;
} | {
    archived: null;
}): ScriptStatus {
    return "scripted" in value ? ScriptStatus.scripted : "idea" in value ? ScriptStatus.idea : "published" in value ? ScriptStatus.published : "recorded" in value ? ScriptStatus.recorded : "archived" in value ? ScriptStatus.archived : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sponsorship: null;
} | {
    merchandise: null;
} | {
    other: string;
} | {
    adsense: null;
} | {
    affiliate: null;
}): {
    __kind__: "sponsorship";
    sponsorship: null;
} | {
    __kind__: "merchandise";
    merchandise: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "adsense";
    adsense: null;
} | {
    __kind__: "affiliate";
    affiliate: null;
} {
    return "sponsorship" in value ? {
        __kind__: "sponsorship",
        sponsorship: value.sponsorship
    } : "merchandise" in value ? {
        __kind__: "merchandise",
        merchandise: value.merchandise
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "adsense" in value ? {
        __kind__: "adsense",
        adsense: value.adsense
    } : "affiliate" in value ? {
        __kind__: "affiliate",
        affiliate: value.affiliate
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    review: null;
} | {
    other: string;
} | {
    educational: null;
} | {
    entertaining: null;
} | {
    tutorial: null;
} | {
    informative: null;
} | {
    motivational: null;
} | {
    commentary: null;
} | {
    storytelling: null;
}): {
    __kind__: "review";
    review: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "educational";
    educational: null;
} | {
    __kind__: "entertaining";
    entertaining: null;
} | {
    __kind__: "tutorial";
    tutorial: null;
} | {
    __kind__: "informative";
    informative: null;
} | {
    __kind__: "motivational";
    motivational: null;
} | {
    __kind__: "commentary";
    commentary: null;
} | {
    __kind__: "storytelling";
    storytelling: null;
} {
    return "review" in value ? {
        __kind__: "review",
        review: value.review
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "educational" in value ? {
        __kind__: "educational",
        educational: value.educational
    } : "entertaining" in value ? {
        __kind__: "entertaining",
        entertaining: value.entertaining
    } : "tutorial" in value ? {
        __kind__: "tutorial",
        tutorial: value.tutorial
    } : "informative" in value ? {
        __kind__: "informative",
        informative: value.informative
    } : "motivational" in value ? {
        __kind__: "motivational",
        motivational: value.motivational
    } : "commentary" in value ? {
        __kind__: "commentary",
        commentary: value.commentary
    } : "storytelling" in value ? {
        __kind__: "storytelling",
        storytelling: value.storytelling
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    finance: null;
} | {
    other: string;
} | {
    entertainment: null;
} | {
    food: null;
} | {
    travel: null;
} | {
    tech: null;
} | {
    education: null;
} | {
    gaming: null;
} | {
    lifestyle: null;
} | {
    health: null;
}): {
    __kind__: "finance";
    finance: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "entertainment";
    entertainment: null;
} | {
    __kind__: "food";
    food: null;
} | {
    __kind__: "travel";
    travel: null;
} | {
    __kind__: "tech";
    tech: null;
} | {
    __kind__: "education";
    education: null;
} | {
    __kind__: "gaming";
    gaming: null;
} | {
    __kind__: "lifestyle";
    lifestyle: null;
} | {
    __kind__: "health";
    health: null;
} {
    return "finance" in value ? {
        __kind__: "finance",
        finance: value.finance
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "entertainment" in value ? {
        __kind__: "entertainment",
        entertainment: value.entertainment
    } : "food" in value ? {
        __kind__: "food",
        food: value.food
    } : "travel" in value ? {
        __kind__: "travel",
        travel: value.travel
    } : "tech" in value ? {
        __kind__: "tech",
        tech: value.tech
    } : "education" in value ? {
        __kind__: "education",
        education: value.education
    } : "gaming" in value ? {
        __kind__: "gaming",
        gaming: value.gaming
    } : "lifestyle" in value ? {
        __kind__: "lifestyle",
        lifestyle: value.lifestyle
    } : "health" in value ? {
        __kind__: "health",
        health: value.health
    } : value;
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Channel>): Array<Channel> {
    return value.map((x)=>from_candid_Channel_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContentIdea>): Array<ContentIdea> {
    return value.map((x)=>from_candid_ContentIdea_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RevenueEntry>): Array<RevenueEntry> {
    return value.map((x)=>from_candid_RevenueEntry_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoScript>): Array<VideoScript> {
    return value.map((x)=>from_candid_VideoScript_n23(_uploadFile, _downloadFile, x));
}
function to_candid_Niche_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Niche): _Niche {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_RevenueSource_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RevenueSource): _RevenueSource {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_ScriptStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScriptStatus): _ScriptStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_ScriptTone_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScriptTone): _ScriptTone {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScriptStatus): {
    scripted: null;
} | {
    idea: null;
} | {
    published: null;
} | {
    recorded: null;
} | {
    archived: null;
} {
    return value == ScriptStatus.scripted ? {
        scripted: null
    } : value == ScriptStatus.idea ? {
        idea: null
    } : value == ScriptStatus.published ? {
        published: null
    } : value == ScriptStatus.recorded ? {
        recorded: null
    } : value == ScriptStatus.archived ? {
        archived: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "sponsorship";
    sponsorship: null;
} | {
    __kind__: "merchandise";
    merchandise: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "adsense";
    adsense: null;
} | {
    __kind__: "affiliate";
    affiliate: null;
}): {
    sponsorship: null;
} | {
    merchandise: null;
} | {
    other: string;
} | {
    adsense: null;
} | {
    affiliate: null;
} {
    return value.__kind__ === "sponsorship" ? {
        sponsorship: value.sponsorship
    } : value.__kind__ === "merchandise" ? {
        merchandise: value.merchandise
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "adsense" ? {
        adsense: value.adsense
    } : value.__kind__ === "affiliate" ? {
        affiliate: value.affiliate
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "review";
    review: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "educational";
    educational: null;
} | {
    __kind__: "entertaining";
    entertaining: null;
} | {
    __kind__: "tutorial";
    tutorial: null;
} | {
    __kind__: "informative";
    informative: null;
} | {
    __kind__: "motivational";
    motivational: null;
} | {
    __kind__: "commentary";
    commentary: null;
} | {
    __kind__: "storytelling";
    storytelling: null;
}): {
    review: null;
} | {
    other: string;
} | {
    educational: null;
} | {
    entertaining: null;
} | {
    tutorial: null;
} | {
    informative: null;
} | {
    motivational: null;
} | {
    commentary: null;
} | {
    storytelling: null;
} {
    return value.__kind__ === "review" ? {
        review: value.review
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "educational" ? {
        educational: value.educational
    } : value.__kind__ === "entertaining" ? {
        entertaining: value.entertaining
    } : value.__kind__ === "tutorial" ? {
        tutorial: value.tutorial
    } : value.__kind__ === "informative" ? {
        informative: value.informative
    } : value.__kind__ === "motivational" ? {
        motivational: value.motivational
    } : value.__kind__ === "commentary" ? {
        commentary: value.commentary
    } : value.__kind__ === "storytelling" ? {
        storytelling: value.storytelling
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "finance";
    finance: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "entertainment";
    entertainment: null;
} | {
    __kind__: "food";
    food: null;
} | {
    __kind__: "travel";
    travel: null;
} | {
    __kind__: "tech";
    tech: null;
} | {
    __kind__: "education";
    education: null;
} | {
    __kind__: "gaming";
    gaming: null;
} | {
    __kind__: "lifestyle";
    lifestyle: null;
} | {
    __kind__: "health";
    health: null;
}): {
    finance: null;
} | {
    other: string;
} | {
    entertainment: null;
} | {
    food: null;
} | {
    travel: null;
} | {
    tech: null;
} | {
    education: null;
} | {
    gaming: null;
} | {
    lifestyle: null;
} | {
    health: null;
} {
    return value.__kind__ === "finance" ? {
        finance: value.finance
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "entertainment" ? {
        entertainment: value.entertainment
    } : value.__kind__ === "food" ? {
        food: value.food
    } : value.__kind__ === "travel" ? {
        travel: value.travel
    } : value.__kind__ === "tech" ? {
        tech: value.tech
    } : value.__kind__ === "education" ? {
        education: value.education
    } : value.__kind__ === "gaming" ? {
        gaming: value.gaming
    } : value.__kind__ === "lifestyle" ? {
        lifestyle: value.lifestyle
    } : value.__kind__ === "health" ? {
        health: value.health
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
